[package]
name = "nrr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "nrr"
path = "src/main.rs"

[[test]]
name = "pak_portable"
path = "tests/pak_portable_entry.rs"

[[test]]
name = "pak_isolated"
path = "tests/pak_isolated.rs"

[dependencies]
nrr-core = { path = "../nrr-core" }
nrr-provider = { path = "../nrr-provider" }
nrr-resolver = { path = "../nrr-resolver" }
nrr-repository = { path = "../nrr-repository" }
percent-encoding.workspace = true
serde.workspace = true
sha2.workspace = true
toml.workspace = true
url.workspace = true
