//! Strict v1 TOML wire codec for the shared logical lock.
//!
//! The DTOs in this module are private implementation details. Domain types
//! remain independent of serde and TOML, and unknown fields are rejected so
//! machine-local materialization facts cannot be silently accepted.

use std::collections::BTreeSet;
use std::error::Error;
use std::fmt;

use serde::{Deserialize, Serialize};

use rsolve_core::{
    EffectiveDependencyKind, EnvironmentId, PackageName, Provenance, PublicationDate,
    RPackageVersion, ReleaseIdentity, RepositoryId, RepositorySubdir, Sha256Digest, SourceScheme,
};

use crate::lock::{LockError, LockedDependencyEdge, LockedPackage, LockedResolution, Lockfile};

const SCHEMA_VERSION: u32 = 1;
const GENERATED_HEADER: &str = "# This file is automatically @generated by rsolve.\n# It is not intended for manual editing.\n\n";

#[derive(Clone, Debug, Eq, PartialEq)]
pub enum LockWireError {
    Parse(String),
    Serialize(String),
    UnsupportedSchema { version: u32 },
    InvalidIdentity(String),
    NonCanonicalVersion { field: String, value: String },
    InvalidField { field: String, message: String },
    Domain(LockError),
}

impl fmt::Display for LockWireError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Parse(message) => write!(formatter, "lock TOML parse failed: {message}"),
            Self::Serialize(message) => {
                write!(formatter, "lock TOML serialization failed: {message}")
            }
            Self::UnsupportedSchema { version } => {
                write!(formatter, "unsupported lock schema version {version}")
            }
            Self::InvalidIdentity(identity) => {
                write!(formatter, "invalid lock identity {identity}")
            }
            Self::NonCanonicalVersion { field, value } => {
                write!(formatter, "non-canonical version in {field}: {value}")
            }
            Self::InvalidField { field, message } => {
                write!(formatter, "invalid lock field {field}: {message}")
            }
            Self::Domain(error) => error.fmt(formatter),
        }
    }
}

impl Error for LockWireError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Domain(error) => Some(error),
            _ => None,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
struct WireLockfile {
    version: u32,
    r_version: String,
    #[serde(
        default = "default_environment",
        skip_serializing_if = "is_default_environment"
    )]
    environment: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    publication_cutoff: Option<String>,
    packages: Vec<WirePackage>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
struct WirePackage {
    name: String,
    version: String,
    source: WireSource,
    metadata_sha256: String,
    dependencies: Vec<WireDependency>,
    visible_repository_ids: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, rename_all = "kebab-case")]
struct WireDependency {
    kind: String,
    package: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields, tag = "kind", rename_all = "kebab-case")]
enum WireSource {
    Registry {
        namespace: String,
    },
    Bioconductor {
        namespace: String,
        release: String,
    },
    Git {
        repository: String,
        commit: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        subdirectory: Option<String>,
    },
    Immutable {
        scheme: String,
        digest: String,
    },
}

/// Decode a strict v1 logical lockfile using its R-only logical target.
pub fn from_toml(input: &str) -> Result<Lockfile, LockWireError> {
    let wire: WireLockfile =
        toml::from_str(input).map_err(|error| LockWireError::Parse(error.to_string()))?;
    if wire.version != SCHEMA_VERSION {
        return Err(LockWireError::UnsupportedSchema {
            version: wire.version,
        });
    }
    let resolution = decode_resolution(wire)?;
    crate::lock::validate_canonical_resolution(&resolution).map_err(LockWireError::Domain)?;
    Lockfile::new(vec![resolution]).map_err(LockWireError::Domain)
}

/// Encode a logical lockfile with deterministic field and collection order.
pub fn to_toml(lockfile: &Lockfile) -> Result<String, LockWireError> {
    // Re-normalize a clone so public field mutation cannot affect byte
    // determinism or bypass domain validation at the wire boundary.
    let normalized = Lockfile::new(lockfile.resolutions.clone()).map_err(LockWireError::Domain)?;
    let resolution = normalized
        .single_resolution()
        .map_err(LockWireError::Domain)?;
    let wire = WireLockfile {
        version: SCHEMA_VERSION,
        r_version: canonical_version(&resolution.target.r_version),
        environment: resolution.environment.to_string(),
        publication_cutoff: resolution.publication_cutoff.map(|date| date.to_string()),
        packages: {
            let selected_names = resolution
                .packages
                .iter()
                .map(|package| package.identity.name().clone())
                .collect::<BTreeSet<_>>();
            resolution
                .packages
                .iter()
                .map(|package| encode_package(package, &selected_names))
                .collect::<Result<Vec<_>, _>>()?
        },
    };
    serialize_wire(&wire)
}

impl Lockfile {
    pub fn from_toml(input: &str) -> Result<Self, LockWireError> {
        from_toml(input)
    }

    pub fn to_toml(&self) -> Result<String, LockWireError> {
        to_toml(self)
    }
}

fn decode_resolution(wire: WireLockfile) -> Result<LockedResolution, LockWireError> {
    let r_version = parse_canonical_r_version_field("r-version", &wire.r_version)?;
    let packages = wire
        .packages
        .into_iter()
        .map(decode_package)
        .collect::<Result<Vec<_>, _>>()?;
    let publication_cutoff = wire
        .publication_cutoff
        .map(|value| {
            PublicationDate::parse(&value)
                .map_err(|error| invalid_field("publication-cutoff", error.to_string()))
        })
        .transpose()?;
    let environment = EnvironmentId::new(wire.environment)
        .map_err(|error| invalid_field("environment", error.to_string()))?;
    Ok(LockedResolution {
        target: rsolve_core::ResolutionTarget::new(r_version),
        environment,
        publication_cutoff,
        packages,
    })
}

fn is_default_environment(environment: &str) -> bool {
    environment == "default"
}

fn default_environment() -> String {
    "default".into()
}

fn decode_package(wire: WirePackage) -> Result<LockedPackage, LockWireError> {
    let name = PackageName::new(wire.name)
        .map_err(|error| invalid_field("package.name", error.to_string()))?;
    let version = parse_version("package.version", &wire.version)?;
    let published_version_spelling = (canonical_version(&version) != wire.version)
        .then(|| wire.version.clone().into_boxed_str());
    let identity = ReleaseIdentity::new(name.clone(), decode_provenance(wire.source, &version)?);
    let metadata_sha256 = Sha256Digest::new(wire.metadata_sha256)
        .map_err(|error| invalid_field("metadata-sha256", error.to_string()))?;
    let dependencies = wire
        .dependencies
        .into_iter()
        .map(|dependency| {
            let kind = decode_dependency_kind(&dependency.kind)?;
            let package = PackageName::new(dependency.package).map_err(|error| {
                invalid_field("package.dependencies.package", error.to_string())
            })?;
            Ok(LockedDependencyEdge { kind, package })
        })
        .collect::<Result<Vec<_>, LockWireError>>()?;
    let visible_repository_ids = wire
        .visible_repository_ids
        .into_iter()
        .map(|value| {
            RepositoryId::new(value)
                .map_err(|error| invalid_field("package.visible-repository-ids", error.to_string()))
        })
        .collect::<Result<Vec<_>, _>>()?;
    Ok(LockedPackage {
        identity,
        version,
        published_version_spelling,
        dependencies,
        visible_repository_ids,
        metadata_sha256,
    })
}

fn encode_package(
    package: &LockedPackage,
    selected_names: &BTreeSet<PackageName>,
) -> Result<WirePackage, LockWireError> {
    let version = package
        .published_version_spelling
        .as_deref()
        .map(str::to_owned)
        .unwrap_or_else(|| canonical_version(&package.version));
    let dependencies = package
        .dependencies
        .iter()
        .filter(|dependency| selected_names.contains(&dependency.package))
        .map(|dependency| WireDependency {
            kind: encode_dependency_kind(dependency.kind).to_owned(),
            package: dependency.package.to_string(),
        })
        .collect::<Vec<_>>();
    Ok(WirePackage {
        name: package.identity.name().to_string(),
        version,
        source: encode_provenance(package.identity.provenance())?,
        metadata_sha256: package.metadata_sha256.to_string(),
        dependencies,
        visible_repository_ids: package
            .visible_repository_ids
            .iter()
            .map(ToString::to_string)
            .collect(),
    })
}

fn serialize_wire(wire: &WireLockfile) -> Result<String, LockWireError> {
    let mut output = format!(
        "{GENERATED_HEADER}version = {}\nr-version = {}\n",
        wire.version,
        toml_string(&wire.r_version)?,
    );
    if !is_default_environment(&wire.environment) {
        output.push_str(&format!(
            "environment = {}\n",
            toml_string(&wire.environment)?
        ));
    }
    if let Some(cutoff) = &wire.publication_cutoff {
        output.push_str(&format!("publication-cutoff = {}\n", toml_string(cutoff)?));
    }
    if wire.packages.is_empty() {
        output.push_str("packages = []\n");
    }
    for package in &wire.packages {
        output.push_str("\n[[packages]]\n");
        output.push_str(&format!("name = {}\n", toml_string(&package.name)?));
        output.push_str(&format!("version = {}\n", toml_string(&package.version)?));
        output.push_str(&format!("source = {}\n", inline_source(&package.source)?));
        output.push_str(&format!(
            "metadata-sha256 = {}\n",
            toml_string(package.metadata_sha256.as_str())?
        ));
        output.push_str(&format!(
            "dependencies = {}\n",
            toml_dependencies(&package.dependencies)?
        ));
        output.push_str(&format!(
            "visible-repository-ids = {}\n",
            toml_array(&package.visible_repository_ids)?
        ));
    }
    Ok(output)
}

fn toml_string(value: &str) -> Result<String, LockWireError> {
    #[derive(Serialize)]
    struct Scalar<'a> {
        value: &'a str,
    }
    toml::to_string(&Scalar { value })
        .map(|serialized| {
            serialized
                .trim_end()
                .trim_start_matches("value = ")
                .to_owned()
        })
        .map_err(|error| LockWireError::Serialize(error.to_string()))
}

fn toml_array(values: &[String]) -> Result<String, LockWireError> {
    #[derive(Serialize)]
    struct Array<'a> {
        values: &'a [String],
    }
    toml::to_string(&Array { values })
        .map(|serialized| {
            serialized
                .trim_end()
                .trim_start_matches("values = ")
                .to_owned()
        })
        .map_err(|error| LockWireError::Serialize(error.to_string()))
}

fn toml_dependencies(values: &[WireDependency]) -> Result<String, LockWireError> {
    let entries = values
        .iter()
        .map(|dependency| {
            Ok(format!(
                "{{ kind = {}, package = {} }}",
                toml_string(&dependency.kind)?,
                toml_string(&dependency.package)?
            ))
        })
        .collect::<Result<Vec<_>, LockWireError>>()?;
    Ok(format!("[{}]", entries.join(", ")))
}

fn decode_dependency_kind(value: &str) -> Result<EffectiveDependencyKind, LockWireError> {
    match value {
        "depends" => Ok(EffectiveDependencyKind::Depends),
        "imports" => Ok(EffectiveDependencyKind::Imports),
        "linking-to" => Ok(EffectiveDependencyKind::LinkingTo),
        "promoted-suggests" => Ok(EffectiveDependencyKind::PromotedSuggests),
        _ => Err(invalid_field(
            "package.dependencies.kind",
            format!("unknown effective dependency kind {value}"),
        )),
    }
}

fn encode_dependency_kind(value: EffectiveDependencyKind) -> &'static str {
    match value {
        EffectiveDependencyKind::Depends => "depends",
        EffectiveDependencyKind::Imports => "imports",
        EffectiveDependencyKind::LinkingTo => "linking-to",
        EffectiveDependencyKind::PromotedSuggests => "promoted-suggests",
    }
}

fn inline_source(source: &WireSource) -> Result<String, LockWireError> {
    let field = |name: &str, value: &str| {
        Ok::<_, LockWireError>(format!("{name} = {}", toml_string(value)?))
    };
    let fields = match source {
        WireSource::Registry { namespace } => {
            vec![field("kind", "registry")?, field("namespace", namespace)?]
        }
        WireSource::Bioconductor { namespace, release } => vec![
            field("kind", "bioconductor")?,
            field("namespace", namespace)?,
            field("release", release)?,
        ],
        WireSource::Git {
            repository,
            commit,
            subdirectory,
        } => {
            let mut fields = vec![field("kind", "git")?, field("repository", repository)?];
            fields.push(field("commit", commit)?);
            if let Some(subdirectory) = subdirectory {
                fields.push(field("subdirectory", subdirectory)?);
            }
            fields
        }
        WireSource::Immutable { scheme, digest } => vec![
            field("kind", "immutable")?,
            field("scheme", scheme)?,
            field("digest", digest)?,
        ],
    };
    Ok(format!("{{ {} }}", fields.join(", ")))
}

fn decode_provenance(
    source: WireSource,
    version: &RPackageVersion,
) -> Result<Provenance, LockWireError> {
    Ok(match source {
        WireSource::Registry { namespace } => Provenance::RegistryRelease {
            namespace: rsolve_core::PackageNamespace::new(namespace)
                .map_err(|error| invalid_field("source.namespace", error.to_string()))?,
            version: version.clone(),
        },
        WireSource::Bioconductor { namespace, release } => Provenance::BioconductorRelease {
            namespace: rsolve_core::PackageNamespace::new(namespace)
                .map_err(|error| invalid_field("source.namespace", error.to_string()))?,
            release: rsolve_core::BioconductorRelease::new(release)
                .map_err(|error| invalid_field("source.release", error.to_string()))?,
            version: version.clone(),
        },
        WireSource::Git {
            repository,
            commit,
            subdirectory,
        } => Provenance::GitCommit {
            repository: rsolve_core::NormalizedGitUrl::new(repository)
                .map_err(|error| invalid_field("source.repository", error.to_string()))?,
            commit: rsolve_core::GitCommitId::new(commit)
                .map_err(|error| invalid_field("source.commit", error.to_string()))?,
            subdirectory: subdirectory
                .map(|value| {
                    RepositorySubdir::new(value)
                        .map_err(|error| invalid_field("source.subdirectory", error.to_string()))
                })
                .transpose()?,
        },
        WireSource::Immutable { scheme, digest } => Provenance::ImmutableSource {
            scheme: SourceScheme::new(scheme)
                .map_err(|error| invalid_field("source.scheme", error.to_string()))?,
            digest: Sha256Digest::new(digest)
                .map_err(|error| invalid_field("source.digest", error.to_string()))?,
        },
    })
}

fn encode_provenance(provenance: &Provenance) -> Result<WireSource, LockWireError> {
    Ok(match provenance {
        Provenance::RegistryRelease { namespace, .. } => WireSource::Registry {
            namespace: namespace.to_string(),
        },
        Provenance::BioconductorRelease {
            namespace, release, ..
        } => WireSource::Bioconductor {
            namespace: namespace.to_string(),
            release: release.to_string(),
        },
        Provenance::GitCommit {
            repository,
            commit,
            subdirectory,
        } => WireSource::Git {
            repository: repository.to_string(),
            commit: commit.to_string(),
            subdirectory: subdirectory.as_ref().map(ToString::to_string),
        },
        Provenance::ImmutableSource { scheme, digest } => WireSource::Immutable {
            scheme: scheme.to_string(),
            digest: digest.to_string(),
        },
        Provenance::RBasePackage { .. } => {
            return Err(LockWireError::InvalidIdentity("R base package".into()));
        }
    })
}

fn parse_version(field: &str, value: &str) -> Result<RPackageVersion, LockWireError> {
    RPackageVersion::parse(value).map_err(|error| invalid_field(field, error.to_string()))
}

fn parse_canonical_r_version_field(
    field: &str,
    value: &str,
) -> Result<RPackageVersion, LockWireError> {
    let version = RPackageVersion::parse_bare(value)
        .map_err(|error| invalid_field(field, error.to_string()))?;
    if canonical_version(&version) != value {
        return Err(LockWireError::NonCanonicalVersion {
            field: field.to_owned(),
            value: value.to_owned(),
        });
    }
    Ok(version)
}

fn canonical_version(version: &RPackageVersion) -> String {
    let mut components = version.components().collect::<Vec<_>>();
    while components.len() > 2 && components.last() == Some(&0) {
        components.pop();
    }
    components
        .iter()
        .map(u32::to_string)
        .collect::<Vec<_>>()
        .join(".")
}

fn invalid_field(field: impl Into<String>, message: impl Into<String>) -> LockWireError {
    LockWireError::InvalidField {
        field: field.into(),
        message: message.into(),
    }
}

#[cfg(test)]
mod tests;
