[package]
name = "rsolve-provider"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
rsolve-core = { path = "../rsolve-core" }
deb822-fast = { workspace = true }
rd-rds = { workspace = true }
flate2 = { workspace = true }
fastrand = { workspace = true }
ruzstd = { workspace = true }
tar = { workspace = true }
ureq = { workspace = true }
url = { workspace = true }
jiff = { workspace = true }
postcard = { workspace = true }
redb = { workspace = true }
cap-fs-ext = { workspace = true }
cap-std = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Storage_FileSystem"] }
