[package]
name = "nrr-provider"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
nrr-core = { path = "../nrr-core" }
deb822-fast = { workspace = true }
rd-rds = { workspace = true }
flate2 = { workspace = true }
tar = { workspace = true }
