use super::*;
use rsolve_core::{
    ArtifactLocator, DeclaredDependency, DependencyKind, DependencySourceConstraint, Distribution,
    DistributionChannel, DistributionMetadata, EnvironmentId, PackageNamespace, Provenance,
    RPackageVersion, RegistryId, ReleaseIdentity, ReleaseMetadata, ReleaseObservation,
    RepositorySubdir, Sha256Digest, SourceArtifact, SourceScheme, UpstreamChecksum,
    VersionConstraint,
};

fn version(value: &str) -> RPackageVersion {
    RPackageVersion::parse(value).unwrap()
}

fn package(value: &str) -> PackageName {
    PackageName::new(value).unwrap()
}

fn identity(name: &str, provenance: Provenance) -> ReleaseIdentity {
    ReleaseIdentity::new(package(name), provenance)
}

fn package_record(name: &str, provenance: Provenance) -> LockedPackage {
    LockedPackage {
        identity: identity(name, provenance),
        version: version("1.0"),
        published_version_spelling: None,
        dependencies: vec![
            package("registry"),
            package("bioc"),
            package("git"),
            package("immutable"),
        ],
        metadata_sha256: Sha256Digest::new("a".repeat(64)).unwrap(),
    }
}

fn logical_lock() -> Lockfile {
    Lockfile::new(vec![LockedResolution {
        target: rsolve_core::ResolutionTarget::new(version("4.4.0")),
        environment: EnvironmentId::new("default").unwrap(),
        publication_cutoff: None,
        packages: vec![
            package_record(
                "registry",
                Provenance::RegistryRelease {
                    namespace: PackageNamespace::new("cran").unwrap(),
                    version: version("1.0"),
                },
            ),
            package_record(
                "bioc",
                Provenance::BioconductorRelease {
                    namespace: PackageNamespace::new("bioc").unwrap(),
                    release: rsolve_core::BioconductorRelease::new("3.20").unwrap(),
                    version: version("1.0"),
                },
            ),
            package_record(
                "git",
                Provenance::GitCommit {
                    repository: rsolve_core::NormalizedGitUrl::new("https://example.test/repo")
                        .unwrap(),
                    commit: rsolve_core::GitCommitId::new(
                        "0123456789abcdef0123456789abcdef01234567",
                    )
                    .unwrap(),
                    subdirectory: Some(RepositorySubdir::new("sub/pkg").unwrap()),
                },
            ),
            package_record(
                "immutable",
                Provenance::ImmutableSource {
                    scheme: SourceScheme::new("sha256").unwrap(),
                    digest: Sha256Digest::new("c".repeat(64)).unwrap(),
                },
            ),
        ],
    }])
    .unwrap()
}

fn empty_wire() -> &'static str {
    "version = 1\nr-version = \"4.4\"\npackages = []\n"
}

#[test]
fn logical_sources_and_flat_projection_round_trip_deterministically() {
    let lock = logical_lock();
    let first = to_toml(&lock).unwrap();
    let decoded = from_toml(&first).unwrap();
    assert_eq!(decoded, lock);
    let second = to_toml(&decoded).unwrap();
    assert_eq!(first, second);
    assert!(first.starts_with(
        "# This file is automatically @generated by rsolve.\n# It is not intended for manual editing.\n\n"
    ));
    assert!(first.contains("version = 1"));
    assert!(!first.contains("schema-version"));
    assert!(!first.contains("schema-revision"));
    assert!(first.contains("kind = \"registry\""));
    assert!(first.contains("kind = \"bioconductor\""));
    assert!(first.contains("kind = \"git\""));
    assert!(first.contains("kind = \"immutable\""));
    assert!(first.contains("source = { kind = \"registry\", namespace = \"cran\" }"));
    assert!(!first.contains("identity"));
    assert!(!first.contains("distributions"));
}

#[test]
fn package_published_spelling_is_preserved_but_r_version_is_canonical() {
    let lock = logical_lock();
    let text = to_toml(&lock).unwrap();
    let alternate = text.replace("version = \"1.0\"", "version = \"1.0.0\"");
    let reparsed = from_toml(&alternate).unwrap();
    assert_eq!(to_toml(&reparsed).unwrap(), alternate);

    assert!(matches!(
        from_toml(&text.replace("r-version = \"4.4\"", "r-version = \"4.4.0\"")),
        Err(LockWireError::NonCanonicalVersion { field, .. }) if field == "r-version"
    ));
}

#[test]
fn one_component_target_r_version_round_trips() {
    let lock = Lockfile::new(vec![LockedResolution {
        target: rsolve_core::ResolutionTarget::new(RPackageVersion::parse_bare("4").unwrap()),
        environment: EnvironmentId::new("default").unwrap(),
        publication_cutoff: None,
        packages: Vec::new(),
    }])
    .unwrap();
    let text = to_toml(&lock).unwrap();
    assert!(text.contains("r-version = \"4\""));
    assert_eq!(from_toml(&text).unwrap(), lock);
}

#[test]
fn publication_cutoff_round_trips_and_is_canonical() {
    let cutoff = PublicationDate::parse("2026-06-24").unwrap();
    let lock = Lockfile::new(vec![LockedResolution {
        target: rsolve_core::ResolutionTarget::new(version("4.4.0")),
        environment: EnvironmentId::new("default").unwrap(),
        publication_cutoff: Some(cutoff),
        packages: Vec::new(),
    }])
    .unwrap();
    let text = to_toml(&lock).unwrap();
    assert!(text.contains("publication-cutoff = \"2026-06-24\""));
    assert_eq!(from_toml(&text).unwrap(), lock);
    assert!(matches!(
        from_toml(&text.replace("2026-06-24", "2026-6-24")),
        Err(LockWireError::InvalidField { field, .. }) if field == "publication-cutoff"
    ));
}

#[test]
fn resolution_projection_excludes_artifacts_and_unselected_dependencies() {
    let name = package("artifactless");
    let release_version = version("1.0");
    let release = rsolve_core::PackageRelease::try_from(ReleaseObservation {
        identity: identity(
            "artifactless",
            Provenance::RegistryRelease {
                namespace: PackageNamespace::new("cran").unwrap(),
                version: release_version.clone(),
            },
        ),
        observed_package: name,
        observed_version: release_version,
        metadata: ReleaseMetadata::default(),
        publication: None,
        declared_dependencies: vec![
            DeclaredDependency::from_parts(
                DependencyKind::Depends,
                package("R"),
                DependencySourceConstraint::Any,
                VersionConstraint::unconstrained(),
            )
            .unwrap(),
            DeclaredDependency::from_parts(
                DependencyKind::Imports,
                package("kept"),
                DependencySourceConstraint::Any,
                VersionConstraint::unconstrained(),
            )
            .unwrap(),
            DeclaredDependency::from_parts(
                DependencyKind::Suggests,
                package("suggested"),
                DependencySourceConstraint::Any,
                VersionConstraint::unconstrained(),
            )
            .unwrap(),
        ],
        distributions: vec![Distribution {
            registry: RegistryId::new("cran").unwrap(),
            channel: DistributionChannel::new("source").unwrap(),
            snapshot: None,
            artifacts: vec![rsolve_core::Artifact::Source(SourceArtifact {
                locator: ArtifactLocator::new("/machine/secret.tar.gz").unwrap(),
                upstream_checksums: vec![UpstreamChecksum::Md5("deadbeef".into())],
                size: Some(4242),
            })],
            observed_metadata: DistributionMetadata::default(),
        }],
    })
    .unwrap();
    let resolution = rsolve_core::Resolution::new(
        rsolve_core::ResolutionTarget::new(version("4.4")),
        vec![rsolve_core::ResolvedPackage::new(
            rsolve_core::SolverKey::InstalledName(package("artifactless")),
            release,
            Vec::new(),
            Vec::new(),
        )],
    );
    let lock =
        Lockfile::from_resolution(&resolution, EnvironmentId::new("default").unwrap()).unwrap();
    let text = to_toml(&lock).unwrap();
    for forbidden in [
        "/machine/secret.tar.gz",
        "deadbeef",
        "4242",
        "suggested",
        "kept",
    ] {
        assert!(!text.contains(forbidden));
    }
    assert!(!text.contains("\"R\""));
}

#[test]
fn reader_requires_version_one_and_rejects_removed_headers_and_wrappers() {
    assert!(from_toml(empty_wire()).is_ok());
    for input in [
        "schema-version = 1\nversion = 1\nr-version = \"4.4\"\npackages = []\n",
        "schema-revision = 1\nversion = 1\nr-version = \"4.4\"\npackages = []\n",
        "version = 1\nr-version = \"4.4\"\npackages = []\nresolutions = []\n",
    ] {
        assert!(matches!(from_toml(input), Err(LockWireError::Parse(_))));
    }
    for version in [0, 2, 3] {
        let input = format!("version = {version}\nr-version = \"4.4\"\npackages = []\n");
        assert!(matches!(
            from_toml(&input),
            Err(LockWireError::UnsupportedSchema { version: found, .. }) if found == version
        ));
    }
}

#[test]
fn dangling_dependency_is_rejected_at_the_lock_boundary() {
    let input = "version = 1\nr-version = \"4.4\"\n[[packages]]\nname = \"foo\"\nversion = \"1.0\"\nsource = { kind = \"registry\", namespace = \"cran\" }\nmetadata-sha256 = \"0000000000000000000000000000000000000000000000000000000000000000\"\ndependencies = [\"missing\"]\n";
    assert!(matches!(
        from_toml(input),
        Err(LockWireError::Domain(LockError::DanglingDependency { package, dependency }))
            if package == "foo" && dependency == "missing"
    ));
}

#[test]
fn metadata_digest_is_required_on_wire_packages() {
    let input = "version = 1\nr-version = \"4.4\"\n[[packages]]\nname = \"foo\"\nversion = \"1.0\"\nsource = { kind = \"registry\", namespace = \"cran\" }\ndependencies = []\n";
    assert!(matches!(from_toml(input), Err(LockWireError::Parse(_))));
}

#[test]
fn unknown_and_machine_local_fields_are_rejected_and_not_emitted() {
    let unknown = "version = 1\nr-version = \"4.4\"\npackages = []\nartifact-url = \"/tmp/a\"\n";
    assert!(matches!(from_toml(unknown), Err(LockWireError::Parse(_))));
    let platform =
        "version = 1\nr-version = \"4.4\"\nos = \"linux\"\narch = \"x86_64\"\npackages = []\n";
    assert!(matches!(from_toml(platform), Err(LockWireError::Parse(_))));
    let package_machine_local = "version = 1\nr-version = \"4.4\"\n[[packages]]\nname = \"foo\"\nversion = \"1.0\"\nsource = { kind = \"registry\", namespace = \"cran\" }\ndependencies = []\nartifact-url = \"/tmp/a\"\n";
    assert!(matches!(
        from_toml(package_machine_local),
        Err(LockWireError::Parse(_))
    ));
    let text = to_toml(&logical_lock()).unwrap();
    for forbidden in [
        "artifact-url",
        "cache-path",
        "link-method",
        "artifact-sha256",
        "size",
        "identity",
        "published-version-spelling",
        "distributions",
        "resolutions",
        "environment",
    ] {
        assert!(!text.contains(forbidden), "unexpected field {forbidden}");
    }
    assert!(!text.contains("\nos = "));
    assert!(!text.contains("\narch = "));
}

#[test]
fn non_default_environment_cannot_be_silently_dropped() {
    let lock = Lockfile::new(vec![LockedResolution {
        target: rsolve_core::ResolutionTarget::new(version("4.4")),
        environment: EnvironmentId::new("other").unwrap(),
        publication_cutoff: None,
        packages: Vec::new(),
    }])
    .unwrap();
    assert!(matches!(
        to_toml(&lock),
        Err(LockWireError::InvalidField { field, .. }) if field == "environment"
    ));
}

#[test]
fn reversed_logical_input_has_identical_wire_bytes() {
    let first = logical_lock();
    let mut resolution = first.resolutions[0].clone();
    resolution.packages.reverse();
    for package in &mut resolution.packages {
        package.dependencies.reverse();
    }
    let second = Lockfile::new(vec![resolution]).unwrap();
    assert_eq!(to_toml(&first).unwrap(), to_toml(&second).unwrap());
}
